### ISSUE TITLE
Strange Error; IndexOutOfBoundsException

### ISSUE THREAD

**Issue by castle-bravo** [stathissideris/ditaa#37]
I recently installed the 0.10 version of ditaa, and when I try to use it, I get the following error message:
```

ditaa version 0.9, Copyright (C) 2004--2009  Efstathios (Stathis) Sideris

Running with options:
Reading file: ./pipeline.txt
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.stathissideris.ascii2image.graphics.DiagramShape.connectEndsToAnchors(DiagramShape.java:688)
	at org.stathissideris.ascii2image.graphics.CompositeDiagramShape.connectEndsToAnchors(CompositeDiagramShape.java:217)
	at org.stathissideris.ascii2image.graphics.Diagram.<init>(Diagram.java:372)
	at org.stathissideris.ascii2image.core.CommandLineConverter.main(CommandLineConverter.java:241)

```
I don't know what to make of this.

**Comment by stathissideris** [comment]
Could you please provide the exact command line that you used?

**Comment by stathissideris** [comment]
Not sure what happened with your version, but 0.11 works as expected, maybe try that instead?
